### ISSUE TITLE
Feature request: only fetch the same remote once, even with multiple projects

### ISSUE THREAD

**Issue by Georgiy-Tugai** [Shinmera/autobuild#12]
In lieu of supporting a deeper hierarchy (project -> branch -> build), I believe that it would be useful to key watchers & copies of upstream to the upstream repo URL (canonicalized if possible).

For example, if there's two projects `clasp-testing` and `clasp-dev`, both of which have the url `https://github.com/drmeister/clasp`, `autobuild/repositories/github.com/drmeister/clasp` would contain a bare repository clone. Then, both `clasp-testing` and `clasp-dev` projects, upon user or watcher request for new commits, would run `git fetch` in that bare repo and create builds in the projects based on that repo rather than fetching upstream twice.

I am unsure of the best way to handle the garbage-collection issue; the simplest option would be to provide the user with a list of downloaded remotes (with buttons to delete one or all). No need for reference-counting; re-download remotes on-demand if they are absent.

This could be extended to submodules -- I would implement this as a helper function or `:build` option which automatically replaces URLs in `.gitmodules` of builds with local file paths (in the same "cache" as the project-repos). This would be preferred to using `git clone --recursive` for two reasons: projects which don't share an upstream may share submodules, and the end-users aren't likely to be using recursive clones.

**Comment by Shinmera** [comment]
I forgot to mention this, but you can now do something like this, albeit the system will not do it automatically for you. Using an `autobuild://project` url will clone it from the location of the repository on disk instead. The updates will then trickle down from the "host" project to the "leech" projects as they all perform a pull.

I'll leave this open since the option to automatically do this where possible or replace the URLs in submodules and so forth would still be a useful thing to have.
